name: rogue_one
environment:
  sdk: ">=1.8.0 <=2.0.0-dev.59.0"
dependencies:
  angel_auth: ^1.1.0
  angel_framework: ^1.1.0
  angel_file_service: ^1.1.0
  angel_hot: ^1.1.0
  angel_security: ^1.0.0
  dart2_constant: ^1.0.0
  glob: ^1.0.0
  watcher: ^0.9.0